// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Index, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Index, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Index, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Index, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Index);
    lv_obj_set_height(ui_Panel1, 177);
    lv_obj_set_flex_grow(ui_Panel1, 1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "อุณหภูมิ");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Kanit22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_arc = lv_arc_create(ui_Panel1);
    lv_obj_set_width(ui_temp_arc, 116);
    lv_obj_set_height(ui_temp_arc, 116);
    lv_obj_set_x(ui_temp_arc, 0);
    lv_obj_set_y(ui_temp_arc, 25);
    lv_obj_set_align(ui_temp_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temp_arc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_temp_arc, 20, 40);
    lv_arc_set_value(ui_temp_arc, 25);

    lv_obj_set_style_bg_color(ui_temp_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_temp_label = lv_label_create(ui_temp_arc);
    lv_obj_set_width(ui_temp_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_label, "25.0");
    lv_obj_set_style_text_font(ui_temp_label, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Index);
    lv_obj_set_height(ui_Panel2, 177);
    lv_obj_set_flex_grow(ui_Panel2, 1);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label3, "ความชื้น");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Kanit22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi_arc = lv_arc_create(ui_Panel2);
    lv_obj_set_width(ui_humi_arc, 116);
    lv_obj_set_height(ui_humi_arc, 116);
    lv_obj_set_x(ui_humi_arc, 0);
    lv_obj_set_y(ui_humi_arc, 25);
    lv_obj_set_align(ui_humi_arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humi_arc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_humi_arc, 50);

    lv_obj_set_style_bg_color(ui_humi_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humi_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_humi_label = lv_label_create(ui_humi_arc);
    lv_obj_set_width(ui_humi_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humi_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humi_label, "50.0");
    lv_obj_set_style_text_font(ui_humi_label, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Index);
    lv_obj_set_height(ui_Panel3, 177);
    lv_obj_set_flex_grow(ui_Panel3, 1);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "หลอดไฟ");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Kanit22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lamp_status_panel = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_lamp_status_panel, 116);
    lv_obj_set_height(ui_lamp_status_panel, 116);
    lv_obj_set_x(ui_lamp_status_panel, 0);
    lv_obj_set_y(ui_lamp_status_panel, 20);
    lv_obj_set_align(ui_lamp_status_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lamp_status_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lamp_status_panel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lamp_status_panel, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lamp_status_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lamp_status_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_lamp_status_panel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lamp_status_panel, lv_color_hex(0x00CF06), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_lamp_status_panel, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_lamp_status_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_lamp_status_panel, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_lamp_status_label = lv_label_create(ui_lamp_status_panel);
    lv_obj_set_width(ui_lamp_status_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lamp_status_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lamp_status_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lamp_status_label, "ปิด");
    lv_obj_set_style_text_font(ui_lamp_status_label, &ui_font_Kanit22, LV_PART_MAIN | LV_STATE_DEFAULT);

}
