// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_temp_arc;
extern lv_obj_t * ui_temp_label;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_humi_arc;
extern lv_obj_t * ui_humi_label;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_lamp_status_panel;
extern lv_obj_t * ui_lamp_status_label;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_Kanit22);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
